// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    string    `gorm:"column:userID;not null;comment:用户唯一ID" json:"userID"`        // 用户唯一ID
	Username  string    `gorm:"column:username;not null;comment:用户名（唯一）" json:"username"`   // 用户名（唯一）
	Password  string    `gorm:"column:password;not null;comment:用户密码（加密后）" json:"password"` // 用户密码（加密后）
	Nickname  string    `gorm:"column:nickname;not null;comment:用户昵称" json:"nickname"`      // 用户昵称
	Email     string    `gorm:"column:email;not null;comment:邮箱地址" json:"email"`            // 邮箱地址
	Phone     string    `gorm:"column:phone;not null;comment:手机号" json:"phone"`             // 手机号
	CreatedAt time.Time `gorm:"column:createdAt;not null;comment:创建时间" json:"createdAt"`    // 创建时间
	UpdatedAt time.Time `gorm:"column:updatedAt;not null;comment:最后修改时间" json:"updatedAt"`  // 最后修改时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
